# Enable C++ support
language: cpp

# Build matrix
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - cmake3
            - libstdc++-4.8-dev
            - freeglut3-dev
      env:
      - C_COMPILER=gcc-5
      - CXX_COMPILER=g++-5
      - CMAKE_SYSTEM_NAME=Linux
      - USE_SYSTEM_GLM=OFF
      - USE_SYSTEM_GLUT=ON
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake3
            - libstdc++-4.8-dev
            - freeglut3-dev
      env: 
      - C_COMPILER=clang-3.7
      - CXX_COMPILER=clang++-3.7
      - CMAKE_SYSTEM_NAME=Linux
      - USE_SYSTEM_GLM=OFF
      - USE_SYSTEM_GLUT=ON
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake3
            - binutils-mingw-w64-x86-64
            - g++-mingw-w64-x86-64
            - gcc-mingw-w64-x86-64
            - mingw-w64-x86-64-dev
      env: 
      - C_COMPILER=x86_64-w64-mingw32-gcc
      - CXX_COMPILER=x86_64-w64-mingw32-g++
      - CMAKE_SYSTEM_NAME=Windows
      - USE_SYSTEM_GLM=OFF
      - USE_SYSTEM_GLUT=OFF
    - os: osx
      compiler: gcc
      env:
      - C_COMPILER=gcc
      - CXX_COMPILER=g++
      - CMAKE_SYSTEM_NAME=Darwin
      - USE_SYSTEM_GLM=OFF
      - USE_SYSTEM_GLUT=ON  
    - os: osx
      compiler: clang
      env:
      - C_COMPILER=clang
      - CXX_COMPILER=clang++
      - CMAKE_SYSTEM_NAME=Darwin
      - USE_SYSTEM_GLM=OFF
      - USE_SYSTEM_GLUT=ON

# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DUSE_SYSTEM_GLM=$USE_SYSTEM_GLM -DUSE_SYSTEM_GLUT=$USE_SYSTEM_GLUT -DCMAKE_SYSTEM_NAME=$CMAKE_SYSTEM_NAME -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER .. && make VERBOSE=1
