# Enable C++ support
language: cpp

# Build matrix
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake3
            - libstdc++-4.8-dev
            - freeglut3-dev
            - libglm-dev
      env:
      - COMPILER=g++-5
      - USE_SYSTEM_GLM=OFF
      - USE_SYSTEM_GLUT=ON
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake3
            - libstdc++-4.8-dev
            - freeglut3-dev
            - libglm-dev
      env: 
      - COMPILER=clang++-3.7
      - USE_SYSTEM_GLM=OFF
      - USE_SYSTEM_GLUT=ON
    - os: osx
      compiler: gcc
      env: 
      - COMPILER=g++
      - USE_SYSTEM_GLM=OFF
      - USE_SYSTEM_GLUT=ON  
    - os: osx
      compiler: clang
      env: 
      - COMPILER=clang++
      - USE_SYSTEM_GLM=OFF
      - USE_SYSTEM_GLUT=ON

# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DUSE_SYSTEM_GLM=$USE_SYSTEM_GLM -DUSE_SYSTEM_GLUT=$USE_SYSTEM_GLUT -DCMAKE_CXX_COMPILER=$COMPILER .. && make
