# Enable C++ support
language: cpp

# Build matrix
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - libstdc++-4.8-dev
      env: COMPILER=g++-5
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake
            - libstdc++-4.8-dev
      env: COMPILER=clang++-3.7
    - os: osx
      compiler: gcc
      env: COMPILER=gcc
    - os: osx
      compiler: clang
      env: COMPILER=clang

# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
